pipeline {
    agent any

    stages {
        stage('Openning') {
            steps {
                sh 'echo "Opening"'
                cleanWs()
                sh 'ls -la'
            }
        }
        stage('w/o docker') {
            steps {
                sh '''
                    echo "Without docker"
                    ls -la
                    touch container-no.txt
                '''
            }
        }
        stage('w/ docker') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true // This is the default value, useful if we want a single workspace for all jobs
                }
            }
            steps {
                sh '''
                    echo "With docker"
                    npm --version
                    ls -la
                    touch container-yes.txt
                '''
            }
        }
    }
}